# Generated by Django 4.2.4 on 2023-08-31 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myblog", "0018_alter_post_post_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
